baseURL = "https://red-team-hugo-vlad.netlify.app/"
languageCode = "en-us"
title = "Red Team Cybersecurity Portofolio"
theme = "grid-side"


[Params.Header]

    name = "Team Cybersecurity Portfolio "
    description = "Made by Gabriel Vlad Luca "
   # email = "your@email.com"
    image = "path/to/your/header/image"

    [Params.Footer]

    [[Params.Footer.List]]

        icon_class = "github"
        icon_link = "https://github.com/Vladlgv/Red-Team-Hugo-Netlify.git"

    [Params.Cells]


    [[Params.Cells.List]]

        name = "Learning Plan"
        link = "/learningplan/"
        image = "/businessplan.jpg"

     [[Params.Cells.List]]

        name = "Personal Progress"
        link = "/personalprogress/"
        image = "/progress.png"
    
    [[Params.Cells.List]]

        name = "R&D Project"
        link = "/posts/"
        image = "/rdproject.png"

    [[Params.Cells.List]]

        name = "Write Ups"
        link = "/writeups/"
        image = "/writeup.jpg"



